import enum, uuid
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, LargeBinary, String, Text, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase): pass
class Role(str, enum.Enum): admin="admin"; platform_admin="platform_admin"; company_admin="company_admin"; agent="agent"
class TicketStatus(str, enum.Enum): new="new"; analysis="analysis"; working="working"; waiting="waiting"; validation="validation"; resolved="resolved"; closed="closed"; cancelled="cancelled"
role_column_type = Enum(Role, native_enum=False, validate_strings=True, length=20)
ticket_status_column_type = Enum(TicketStatus, native_enum=False, validate_strings=True, length=30)
class Tenant(Base):
    __tablename__="tenants"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); name:Mapped[str]=mapped_column(String(120)); public_slug:Mapped[str]=mapped_column(String(80),unique=True,index=True); active:Mapped[bool]=mapped_column(Boolean,default=True)
class Area(Base):
    __tablename__="areas"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); name:Mapped[str]=mapped_column(String(120)); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class User(Base):
    __tablename__="users"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); area_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("areas.id"),nullable=True,index=True); email:Mapped[str]=mapped_column(String(254)); name:Mapped[str]=mapped_column(String(120)); password_hash:Mapped[str]=mapped_column(Text); role:Mapped[Role]=mapped_column(role_column_type); avatar_data:Mapped[bytes|None]=mapped_column(LargeBinary,nullable=True); avatar_content_type:Mapped[str|None]=mapped_column(String(40),nullable=True); active:Mapped[bool]=mapped_column(Boolean,default=True); deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Ticket(Base):
    __tablename__="tickets"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); area_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("areas.id"),index=True); protocol:Mapped[int]=mapped_column(index=True); requester_name:Mapped[str]=mapped_column(String(120)); department:Mapped[str]=mapped_column(String(120)); contact:Mapped[str|None]=mapped_column(String(254),nullable=True); title:Mapped[str]=mapped_column(String(180)); summary:Mapped[str]=mapped_column(Text); product:Mapped[str]=mapped_column(String(80)); priority:Mapped[str]=mapped_column(String(20),default="normal"); status:Mapped[TicketStatus]=mapped_column(ticket_status_column_type,default=TicketStatus.new); public_token_hash:Mapped[str]=mapped_column(String(64)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class TicketStatusHistory(Base):
    __tablename__="ticket_status_history"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); ticket_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tickets.id",ondelete="CASCADE"),index=True); status:Mapped[TicketStatus]=mapped_column(ticket_status_column_type); changed_by:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("users.id"),nullable=True); entered_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Resolution(Base):
    __tablename__="resolutions"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); ticket_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tickets.id"),unique=True); confirmed_problem:Mapped[str]=mapped_column(Text); root_cause:Mapped[str]=mapped_column(Text); solution:Mapped[str]=mapped_column(Text); validation:Mapped[str]=mapped_column(Text); reusable:Mapped[bool]=mapped_column(Boolean,default=False); sanitized_document:Mapped[dict|None]=mapped_column(JSONB,nullable=True)
class AIConfig(Base):
    __tablename__="ai_configs"; tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),primary_key=True); provider:Mapped[str]=mapped_column(String(30),default="ollama"); model:Mapped[str]=mapped_column(String(120)); embedding_model:Mapped[str]=mapped_column(String(120)); conversation_source:Mapped[str]=mapped_column(String(20),default="ollama"); embedding_source:Mapped[str]=mapped_column(String(20),default="ollama"); api_base_url:Mapped[str|None]=mapped_column(String(500),nullable=True); api_key_encrypted:Mapped[bytes|None]=mapped_column(LargeBinary,nullable=True); context_size:Mapped[int]=mapped_column(default=8192); max_tokens:Mapped[int]=mapped_column(default=512); temperature:Mapped[str]=mapped_column(String(8),default="0.2"); response_timeout_seconds:Mapped[int]=mapped_column(default=90); valid_response_rules:Mapped[dict]=mapped_column(JSONB,default=dict); runtime_profiles:Mapped[dict]=mapped_column(JSONB,default=dict)
class Skill(Base):
    __tablename__="skills"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); name:Mapped[str]=mapped_column(String(160)); source_url:Mapped[str]=mapped_column(String(1000)); content:Mapped[str]=mapped_column(Text); sha256:Mapped[str]=mapped_column(String(64)); scope:Mapped[str]=mapped_column(String(20),default="all"); active:Mapped[bool]=mapped_column(Boolean,default=False); created_by:Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id")); last_test_model:Mapped[str|None]=mapped_column(String(120),nullable=True); last_test_success:Mapped[bool|None]=mapped_column(Boolean,nullable=True); last_test_ms:Mapped[int|None]=mapped_column(nullable=True); last_test_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class KnowledgeDocument(Base):
    __tablename__="knowledge_documents"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); area_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("areas.id"),index=True); title:Mapped[str]=mapped_column(String(180)); filename:Mapped[str]=mapped_column(String(255)); content_type:Mapped[str]=mapped_column(String(100)); sha256:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(20),default="active"); uploaded_by:Mapped[uuid.UUID]=mapped_column(ForeignKey("users.id")); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class KnowledgeChunk(Base):
    __tablename__="knowledge_chunks"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); document_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("knowledge_documents.id",ondelete="CASCADE"),index=True); chunk_index:Mapped[int]=mapped_column(); content:Mapped[str]=mapped_column(Text)
class UsageEvent(Base):
    __tablename__="usage_events"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); event_type:Mapped[str]=mapped_column(String(40)); model:Mapped[str|None]=mapped_column(String(120),nullable=True); success:Mapped[bool]=mapped_column(Boolean,default=True); duration_ms:Mapped[int|None]=mapped_column(nullable=True); prompt_tokens:Mapped[int|None]=mapped_column(nullable=True); response_tokens:Mapped[int|None]=mapped_column(nullable=True); tokens_estimated:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class TicketAttachment(Base):
    __tablename__="ticket_attachments"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); ticket_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tickets.id",ondelete="CASCADE"),index=True); filename:Mapped[str]=mapped_column(String(255)); content_type:Mapped[str]=mapped_column(String(40)); size_bytes:Mapped[int]=mapped_column(); data:Mapped[bytes]=mapped_column(LargeBinary); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class AuditLog(Base):
    __tablename__="audit_logs"; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uuid.uuid4); tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("tenants.id"),index=True); actor_user_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("users.id"),nullable=True,index=True); actor_role:Mapped[str]=mapped_column(String(20)); action:Mapped[str]=mapped_column(String(80),index=True); target_type:Mapped[str]=mapped_column(String(40)); target_id:Mapped[str|None]=mapped_column(String(80),nullable=True); details:Mapped[dict]=mapped_column(JSONB,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
